[package]
name = "midi_inverter"
version = "0.1.0"
edition.workspace = true
authors = ["Robbert van der Helm <mail@robbertvanderhelm.nl>"]
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { path = "../../crates/nih_plug", features = [
    "assert_process_allocs",
    "auv2",
] }
